name: binge_box
description: "Movie App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  retrofit: ^4.6.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  freezed: ^3.0.6
  injectable: ^2.5.1
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  auto_route: ^10.1.0+1
  cached_network_image: ^3.4.1
  shimmer_animation: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed_annotation: ^3.1.0
  injectable_generator: ^2.7.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  retrofit_generator:
  auto_route_generator:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
